local WordManager = {}

WordManager.bank = {
    {category="Gradovi", word="DUBROVNIK"},
{category="Gradovi", word="ZAGREB"},
{category="Gradovi", word="SPLIT"},
{category="Gradovi", word="RIJEKA"},
{category="Gradovi", word="OSIJEK"},
{category="Gradovi", word="ZADAR"},
{category="Gradovi", word="PULA"},
{category="Gradovi", word="VUKOVAR"},
{category="Gradovi", word="LONDON"},
{category="Gradovi", word="PARIZ"},
{category="Gradovi", word="BERLIN"},
{category="Gradovi", word="TOKIO"},
{category="Gradovi", word="NEW YORK"},
{category="Gradovi", word="AMSTERDAM"},
{category="Gradovi", word="RIM"},

{category="Države", word="HRVATSKA"},
{category="Države", word="ITALIJA"},
{category="Države", word="SLOVENIJA"},
{category="Države", word="DANSKA"},
{category="Države", word="FINSKA"},
{category="Države", word="PORTUGAL"},
{category="Države", word="JAPAN"},
{category="Države", word="KANADA"},
{category="Države", word="ARGENTINA"},
{category="Države", word="AUSTRALIJA"},
{category="Države", word="MAROKO"},

{category="Tech", word="UMJETNA INTELIGENCIJA"},
{category="Tech", word="PROGRAMIRANJE"},
{category="Tech", word="ALGORITAM"},
{category="Tech", word="INTERNET"},
{category="Tech", word="HARDVER"},
{category="Tech", word="SOFTVER"},
{category="Tech", word="PROCESOR"},
{category="Tech", word="MONITOR"},
{category="Tech", word="TIPKOVNICA"},
{category="Tech", word="LINUX"},
{category="Tech", word="PYTHON"},
{category="Tech", word="SERVER"},
{category="Tech", word="BAZA PODATAKA"},

{category="Životinje", word="KROKODIL"},
{category="Životinje", word="ALIGATOR"},
{category="Životinje", word="PINGVIN"},
{category="Životinje", word="SLON"},
{category="Životinje", word="TIGAR"},
{category="Životinje", word="LAV"},
{category="Životinje", word="ZEBRA"},
{category="Životinje", word="GORILA"},
{category="Životinje", word="MORSKI PAS"},
{category="Životinje", word="JASTREB"},
{category="Životinje", word="BOGOMOLJKA"},
{category="Životinje", word="LEOPARD"},
{category="Životinje", word="ANAKONDA"},
{category="Životinje", word="HOBOTNICA"},

{category="Filmovi", word="MATRIX"},
{category="Filmovi", word="TITANIK"},
{category="Filmovi", word="AVATAR"},
{category="Filmovi", word="TERMINATOR"},
{category="Filmovi", word="GLADIJATOR"},
{category="Filmovi", word="GOSPODAR PRSTENOVA"},
{category="Filmovi", word="HARRY POTTER"},
{category="Filmovi", word="RATOVI ZVIJEZDA"},
{category="Filmovi", word="BATMAN"},
{category="Filmovi", word="SPIDERMAN"},
{category="Filmovi", word="JURASSIC PARK"},
{category="Filmovi", word="INCEPTION"},
{category="Filmovi", word="FORREST GUMP"},

{category="Sport", word="NOGOMET"},
{category="Sport", word="RUKOMET"},
{category="Sport", word="TENIS"},
{category="Sport", word="VATERPOLO"},
{category="Sport", word="ODBOJKA"},
{category="Sport", word="BADMINTON"},
{category="Sport", word="KARATE"},
{category="Sport", word="FORMULA JEDAN"},
{category="Sport", word="ATLETIKA"},

{category="Hrana", word="PIZZA"},
{category="Hrana", word="BURGER"},
{category="Hrana", word="TORTILJA"},
{category="Hrana", word="SARMA"},
{category="Hrana", word="BUREK"},
{category="Hrana", word="ANANAS"},
{category="Hrana", word="JAGODA"},
{category="Hrana", word="LUBENICA"},
{category="Hrana", word="BROKULA"},
{category="Hrana", word="PAPRIKA"},
{category="Hrana", word="KOKICE"},

}

function WordManager.getRandom()
    return WordManager.bank[love.math.random(1, #WordManager.bank)]
end

return WordManager
